import { InputProvider } from '@/providers/InputProvider'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <InputProvider>
        <body className="bg-gray-800 text-white">{children}</body>
      </InputProvider>
    </html>
  )
}
